#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: spike-gateway
#spec:
#  selector:
#    istio: ingressgateway # use istio default controller
#  servers:
#  - port:
#      number: 80
#      name: http
#     protocol: HTTP
#    hosts:
#    - "spike-canary.pogoapps.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary-demo-vs
spec:
  gateways:
  - istio-system/monitoring-gateway
  hosts:
  - "spike-canary.pogoapps.com"
  http:
  - name: primary
    route:
    - destination:
        host: {{ .Values.service.name }}-stable
        port:
          number: 8080
      weight: 100
    - destination:
        host: {{ .Values.service.name }}-canary
        port:
          number: 8080
      weight: 0
