apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ .Values.service.name }}
namespace: canary-demo
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  strategy:
    canary:
      canaryService: {{ .Values.service.name }}-canary
      stableService: {{ .Values.service.name }}-stable
      trafficRouting:
        istio:
          virtualService:
            name: canary-demo-vs
            routes:
            - primary # At least one route is required
      steps:
      - setWeight: 10
      - pause:
          duration: 1m
      - setWeight: 90
      - pause: {}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: {{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
