---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-canary
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-stable
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
---
